language: python

matrix:
  include:
    - os: linux
      python:
        "3.7"
            
      install: 
        - python3 ./setup.py install
      
      script:
        - cd utest
        - ./start.py